name=Epson_SU_UART
version=2.0.1
author=Sensing System Support, sensingsystem_support@ea.epson.com
maintainer=Sensing System Support, sensingsystem_support@ea.epson.com
sentence=Sensing Unit Library using UART for Epson IMU M-Gxxx & Accelerometer/Vibration sensor M-Axxx
paragraph=Basic device library for configuring, initializing, retrieving sensor data with Epson M-Gxxx/M-Axxx connected by UART interface
category=Sensors
url=https://www.epsondevice.com/sensing/en/
architectures=*
